<div id="skillpool" hidden>

</div>

<div>
	<table id="resumelist" class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>名字</th>
				<th>性别</th>
				<th>学历</th>
				<th>电话</th>
				<th>邮箱</th>
				<th>工作时间</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th>1</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th>3</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>2</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th>3</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>3</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th>3</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>4</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th>3</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>5</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th>3</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>			
		</tbody>
	</table>
</div>