<div>
	<table id="resumelist" class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Age</th>
				<th>Education</th>
				<th>Experience</th>
				<th>Resume</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th>1</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>2</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>3</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>4</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>
			<tr>
				<th>5</th>
				<th>Test</th>
				<th>34</th>
				<th>Master</th>
				<th>3</th>
				<th><button>View</button></th>
			</tr>			
		</tbody>
	</table>
</div>